name: shartflix
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  easy_localization: ^3.0.8
  equatable: ^2.0.7
  firebase_analytics: ^11.6.0
  firebase_core: ^3.15.2
  firebase_crashlytics: ^4.3.10
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.10+1
  get_it: ^8.0.3
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  logger: ^2.6.1
  lottie: ^3.3.1
  retrofit: ^4.6.0

dev_dependencies:
  build_runner: ^2.5.4
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5
  retrofit_generator: ^10.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/sinFlixLogo.png"
flutter_native_splash:
  color: "#000000"
  image_android: assets/SinFlixSplash-BG.png
  android_gravity: fill|clip_horizontal

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Euclid Circular A
      fonts:
        - asset: assets/fonts/Euclid Circular A Light.ttf
          weight: 300
        - asset: assets/fonts/Euclid Circular A Light Italic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Euclid Circular A Regular.ttf
          weight: 400
        - asset: assets/fonts/Euclid Circular A Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Euclid Circular A Medium.ttf
          weight: 500
        - asset: assets/fonts/Euclid Circular A Medium Italic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Euclid Circular A SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Euclid Circular A SemiBold Italic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Euclid Circular A Bold.ttf
          weight: 700
        - asset: assets/fonts/Euclid Circular A Bold Italic.ttf
          weight: 700
          style: italic
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
